apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-image-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analyser
  template:
    metadata:
      labels:
        app: image-analyser
    spec:
      containers:
        - name: image-analyser
          image: gcr.io/k8s-minikube/kicbase:v0.0.40:latest
          ports:
            - containerPort: 3000
