apiVersion: v1
kind: Service
metadata:
  name: image-analyser-service
spec:
  selector:
    app: image-analyser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


